const BaseActorTrainer = require('./BaseActorTrainer');
const { formatDateVN } = require('../utils/dateHelper');
const ROLES = ['QC', 'QA', 'QUALITY_CONTROL', 'ADMIN_CEO', 'ADMIN'];
const trainer = new BaseActorTrainer({ role: 'QC', name: 'Kiểm định chất lượng (QA/QC)', systemPrompt: 'Bạn là trợ lý QA/QC AetherPC. Ưu tiên kiểm định PO, đối chiếu số lượng, serial, seal và xử lý RMA theo biên bản.' });

trainer.addSkill({ id: 'QC_DASHBOARD_SUMMARY', title: 'Tổng quan nhiệm vụ kiểm định QA/QC', examples: ['tổng quan kiểm định chất lượng hôm nay', 'dashboard qa qc có gì cần xử lý', 'hiện tại có bao nhiêu lô hàng chờ kiểm định', 'tình hình nghiệm thu po và rma', 'tỷ lệ đạt chuẩn qa hiện tại là bao nhiêu'], patterns: [/(tổng quan.*(qa|qc|kiểm định)|dashboard.*(qa|qc)|tỷ lệ đạt chuẩn|tình hình.*(nghiệm thu|rma))/i], allowedRoles: ROLES,
  handler: async prisma => { const [pendingPo, passedPo, partialPo, rejectedPo, pendingRma, total] = await Promise.all([prisma.purchaseOrder.count({ where: { status: 'PENDING_QA' } }), prisma.purchaseOrder.count({ where: { status: 'QA_PASSED' } }), prisma.purchaseOrder.count({ where: { status: 'QA_PARTIAL' } }), prisma.purchaseOrder.count({ where: { status: 'QA_REJECTED' } }), prisma.returnRequest.count({ where: { status: 'DELIVERED_TO_WAREHOUSE' } }), prisma.qcInspection.aggregate({ _sum: { passedQuantity: true, defectiveQuantity: true } })]); const passed = total._sum.passedQuantity || 0; const defective = total._sum.defectiveQuantity || 0; return { pendingPo, passedPo, partialPo, rejectedPo, pendingRma, passed, defective, rate: passed + defective ? passed * 100 / (passed + defective) : null }; },
  template: d => `🛡️ **TỔNG QUAN QA/QC**\n\n- PO chờ nghiệm thu: **${d.pendingPo}**\n- Đạt 100%: **${d.passedPo}** | Đạt một phần: **${d.partialPo}** | Không đạt: **${d.rejectedPo}**\n- RMA về kho chờ thẩm định: **${d.pendingRma}**\n- Số lượng đã kiểm: **${d.passed} đạt / ${d.defective} lỗi**\n- Tỷ lệ đạt QA: **${d.rate === null ? 'Chưa có biên bản' : d.rate.toFixed(1) + '%'}**` });

trainer.addSkill({ id: 'PENDING_PO_INSPECTIONS', title: 'Lô PO đang chờ kiểm định', examples: ['danh sách lô hàng po chờ kiểm định', 'po nào đang chờ nghiệm thu qa qc', 'hàng nhập nào cần kiểm tra ngay', 'có lô hàng nào vừa giao tới chờ qc không', 'xem các phiếu nhập đang pending qa'], patterns: [/(po|hàng nhập|lô hàng).*(chờ.*(kiểm định|nghiệm thu)|pending.*qa)|(kiểm định|nghiệm thu).*(po|hàng nhập)/i], allowedRoles: ROLES,
  handler: prisma => prisma.purchaseOrder.findMany({ where: { status: 'PENDING_QA' }, select: { poNumber: true, totalAmount: true, supplier: { select: { name: true } }, receipts: { select: { receiptNumber: true }, take: 1 }, items: { select: { quantity: true } } }, orderBy: { updatedAt: 'asc' }, take: 20 }),
  template: rows => !rows.length ? '✅ Không có lô PO nào đang chờ QA/QC nghiệm thu.' : `⏳ **${rows.length} LÔ PO ĐANG CHỜ KIỂM ĐỊNH**\n\n` + rows.map((p, i) => `${i + 1}. **${p.poNumber}** — ${p.supplier.name}\n   Số lượng: **${p.items.reduce((s, x) => s + x.quantity, 0)}** | Giá trị: **${Number(p.totalAmount).toLocaleString('vi-VN')} đ**\n   Phiếu nhận: ${p.receipts[0]?.receiptNumber || 'Chưa có mã'}`).join('\n\n') });

trainer.addSkill({ id: 'PO_INSPECTION_DETAIL', title: 'Chi tiết kiểm định một PO', requiredParams: ['poNumber'], examples: ['xem chi tiết kiểm định PO-261003-1387', 'kiểm tra kết quả nghiệm thu po PO-2026-0010', 'biên bản qa của po PO-260925-1217', 'lô PO-261003-1387 đã đạt chưa'], patterns: [/(chi tiết|kết quả|biên bản|kiểm tra|tra cứu).*(po[-_]?\w+)/i], allowedRoles: ROLES,
  handler: (prisma, p) => prisma.purchaseOrder.findUnique({ where: { poNumber: p.poNumber }, select: { poNumber: true, status: true, supplier: { select: { name: true } }, items: { select: { quantity: true, product: { select: { name: true } } } }, receipts: { select: { qcInspections: { select: { status: true, passedQuantity: true, defectiveQuantity: true, notes: true, inspectedAt: true }, take: 1 } } } }),
  template: po => { if (!po) return '❌ Không tìm thấy PO này.'; const q = po.receipts.flatMap(r => r.qcInspections)[0]; return `🔎 **KIỂM ĐỊNH ${po.poNumber}**\n- NCC: **${po.supplier.name}** | Trạng thái: **${po.status}**\n- Hàng: ${po.items.map(x => x.product.name + ' ×' + x.quantity).join('; ')}\n- Biên bản: ${q ? `**${q.status}** — ${q.passedQuantity} đạt / ${q.defectiveQuantity} lỗi\n- ${formatDateVN(q.inspectedAt)}\n- Ghi chú: ${q.notes || 'Không có'}` : 'Chưa có biên bản'}`; } });

trainer.addSkill({ id: 'PENDING_RMA_INSPECTIONS', title: 'RMA đang chờ QC thẩm định', examples: ['danh sách hàng đổi trả chờ qc thẩm định', 'rma nào đã về kho chưa kiểm tra', 'có bao nhiêu yêu cầu đổi trả cần kiểm định', 'hàng bảo hành nào đang chờ qc xử lý'], patterns: [/(rma|đổi trả|bảo hành).*(chờ.*(qc|thẩm định|kiểm tra)|đã về kho)|(hàng.*trả về).*(kiểm tra|thẩm định)/i], allowedRoles: ROLES,
  handler: prisma => prisma.returnRequest.findMany({ where: { status: 'DELIVERED_TO_WAREHOUSE' }, select: { rmaCode: true, orderId: true, type: true, reason: true, customerName: true, order: { select: { items: { select: { name: true, quantity: true } } } } }, take: 20 }),
  template: rows => !rows.length ? '✅ Không có hàng RMA nào đang chờ QC thẩm định.' : `🧾 **${rows.length} RMA CHỜ THẨM ĐỊNH**\n\n` + rows.map((r, i) => `${i + 1}. **${r.rmaCode || r.orderId}** — ${r.type}\n   Khách: ${r.customerName || 'Chưa cập nhật'} | Lý do: ${r.reason}\n   Hàng: ${r.order.items.map(x => x.name + ' ×' + x.quantity).join(', ')}`).join('\n\n') });

trainer.addSkill({ id: 'RMA_INSPECTION_DETAIL', title: 'Kết quả thẩm định RMA', requiredParams: ['rmaCode'], examples: ['kiểm tra kết quả rma RMA-260917-4821', 'rma RMA-260917-4821 qc kết luận gì', 'chi tiết thẩm định bảo hành RMA-120985', 'hàng đổi trả RMA-019784 có lỗi gì'], patterns: [/(kết quả|chi tiết|quyết định|lỗi).*(rma[-_]?\w+)|(rma[-_]?\w+).*(qc|lỗi|kết luận)/i], allowedRoles: ROLES,
  handler: (prisma, p) => prisma.returnRequest.findUnique({ where: { rmaCode: p.rmaCode }, select: { rmaCode: true, orderId: true, type: true, status: true, reason: true, qcDecision: true, qcDefectType: true, qcNotes: true } }),
  template: r => !r ? '❌ Không tìm thấy phiếu RMA này.' : `🛡️ **THẨM ĐỊNH RMA ${r.rmaCode}**\n- Đơn gốc: **${r.orderId}** | Trạng thái: **${r.status}**\n- Hình thức: ${r.type}\n- Lý do: ${r.reason}\n- Kết luận QC: **${r.qcDecision || 'Chưa thẩm định'}**\n- Dạng lỗi: ${r.qcDefectType || 'Chưa xác định'}\n- Ghi chú: ${r.qcNotes || 'Không có'}` });

trainer.addSkill({ id: 'QC_RECENT_RECORDS', title: 'Nhật ký và biên bản kiểm định gần đây', examples: ['xem nhật ký kiểm định gần đây', 'danh sách biên bản qa mới nhất', 'hôm nay qc đã nghiệm thu những lô nào', 'xem các lô hàng kiểm định bị lỗi', 'lịch sử kiểm định chất lượng'], patterns: [/(nhật ký|lịch sử|biên bản).*(qa|qc|kiểm định|nghiệm thu)|(kiểm định|nghiệm thu).*(gần đây|hôm nay|bị lỗi)/i], allowedRoles: ROLES,
  handler: (prisma, p) => prisma.qcInspection.findMany({ where: p.hasDate ? { inspectedAt: { gte: p.startDate, lte: p.endDate } } : undefined, select: { status: true, passedQuantity: true, defectiveQuantity: true, notes: true, inspectedAt: true, receipt: { select: { po: { select: { poNumber: true, supplier: { select: { name: true } } } } } } }, orderBy: { inspectedAt: 'desc' }, take: 20 }),
  template: rows => !rows.length ? 'Không có biên bản kiểm định nào trong khoảng thời gian này.' : `📋 **${rows.length} BIÊN BẢN KIỂM ĐỊNH GẦN ĐÂY**\n\n` + rows.map((r, i) => `${i + 1}. **${r.receipt?.po?.poNumber || 'Không rõ PO'}** — ${r.status}\n   ${r.receipt?.po?.supplier?.name || 'Chưa rõ NCC'} | ${r.passedQuantity} đạt / ${r.defectiveQuantity} lỗi | ${formatDateVN(r.inspectedAt)}${r.notes ? '\n   Ghi chú: ' + r.notes : ''}`).join('\n\n') });

trainer.addSkill({ id: 'SOP_INBOUND_QC_CHECKLIST', title: 'Checklist kiểm định hàng nhập PO', type: 'KNOWLEDGE_SOP', examples: ['quy trình kiểm định hàng nhập po', 'checklist qc khi nhận hàng từ nhà cung cấp', 'cần kiểm tra gì trước khi cho nhập kho', 'quy trình nghiệm thu lô hàng'], patterns: [/(quy trình|checklist).*(kiểm định|nghiệm thu|hàng nhập|po)|kiểm tra gì.*nhập kho/i], allowedRoles: ROLES, sop: '🛡️ **CHECKLIST KIỂM ĐỊNH HÀNG NHẬP**\n1. Đối chiếu PO, phiếu nhận, NCC, mã hàng và số lượng.\n2. Kiểm tra ngoại quan, thùng hộp, seal/tem, phụ kiện.\n3. Đối chiếu serial/part number và kiểm tra mẫu.\n4. Ghi số đạt/lỗi, dạng lỗi, ảnh minh chứng.\n5. Đạt toàn phần thì nhập kho; đạt một phần chỉ nhập số đạt; không đạt thì cách ly và trả NCC.' });
trainer.addSkill({ id: 'SOP_RMA_QC_DECISION', title: 'Quy trình thẩm định RMA và đổi trả', type: 'KNOWLEDGE_SOP', examples: ['quy trình qc thẩm định hàng đổi trả', 'rma về kho cần kiểm tra gì', 'khi nào nhập lại kho hàng đổi trả', 'tiêu chí từ chối bảo hành rma'], patterns: [/(quy trình|tiêu chí).*(rma|đổi trả|bảo hành)|rma.*kiểm tra gì|nhập lại kho.*đổi trả/i], allowedRoles: ROLES, sop: '🔁 **THẨM ĐỊNH RMA**\n1. Đối chiếu RMA, đơn gốc, serial và ảnh minh chứng.\n2. Hàng nguyên seal/không lỗi đủ điều kiện: nhập lại kho.\n3. Lỗi phần cứng NSX: ghi rõ lỗi, đổi mới hoặc chuyển bảo hành NCC.\n4. Hàng rơi vỡ, vào nước, cháy nổ hoặc can thiệp trái quy định: lưu ảnh và từ chối rõ ràng.\n5. Chỉ hoàn tiền/đổi mới khi biên bản QC đầy đủ.' });
module.exports = trainer;
